/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.editordetexto;

import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import static java.lang.Integer.parseInt;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.event.ChangeListener;

/**
 *
 * @author david
 */
public class Ventana extends javax.swing.JFrame {

    //Atributos
    private JFileChooser fc = new JFileChooser();
    private File archivo;
    private Color colorFuente = Color.BLACK;
    private String tamanhoFuente = "";
    
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hechoPor = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        colorChooser = new javax.swing.JDialog();
        colorSeleccionado = new javax.swing.JColorChooser();
        seleccionarColor = new javax.swing.JButton();
        fontChooser = new javax.swing.JDialog();
        fontSize = new javax.swing.JTextField();
        seleccionarTamanho = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        info = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        abrir = new javax.swing.JMenuItem();
        guardar = new javax.swing.JMenuItem();
        guardarComo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        salir = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        fuente = new javax.swing.JMenuItem();
        color = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        autor = new javax.swing.JMenuItem();

        hechoPor.setPreferredSize(new java.awt.Dimension(400, 200));
        hechoPor.getContentPane().setLayout(new javax.swing.BoxLayout(hechoPor.getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setText("Hecho por David Ramos Navas");
        hechoPor.getContentPane().add(jLabel1);

        jTextField1.setText("https://github.com/DavidRN01/Editor-de-Texto.git");
        hechoPor.getContentPane().add(jTextField1);

        colorChooser.getContentPane().add(colorSeleccionado, java.awt.BorderLayout.CENTER);

        seleccionarColor.setText("Seleccionar Color");
        seleccionarColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarColorActionPerformed(evt);
            }
        });
        colorChooser.getContentPane().add(seleccionarColor, java.awt.BorderLayout.PAGE_END);

        fontChooser.getContentPane().add(fontSize, java.awt.BorderLayout.CENTER);

        seleccionarTamanho.setText("Seleccionar Tamaño");
        seleccionarTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarTamanhoActionPerformed(evt);
            }
        });
        fontChooser.getContentPane().add(seleccionarTamanho, java.awt.BorderLayout.PAGE_END);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        texto.setColumns(20);
        texto.setRows(5);
        jScrollPane1.setViewportView(texto);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        info.setText("Tamaño: Ubicación:");
        getContentPane().add(info, java.awt.BorderLayout.PAGE_END);

        jMenu1.setText("Archivo");

        abrir.setText("Abrir");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });
        jMenu1.add(abrir);

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jMenu1.add(guardar);

        guardarComo.setText("Guardar como");
        guardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarComoActionPerformed(evt);
            }
        });
        jMenu1.add(guardarComo);
        jMenu1.add(jSeparator1);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jMenu1.add(salir);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Formato");

        fuente.setText("Fuente");
        fuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuenteActionPerformed(evt);
            }
        });
        jMenu3.add(fuente);

        color.setText("Color");
        color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorActionPerformed(evt);
            }
        });
        jMenu3.add(color);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Acerca de...");

        autor.setText("Hecho por...");
        autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorActionPerformed(evt);
            }
        });
        jMenu2.add(autor);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        
        //Creo la ventana para seleccionar archivos
        int status = fc.showOpenDialog(null);
        
        if(status == JFileChooser.APPROVE_OPTION) {
            //Creo el objeto tipo file y le asigno el que sea seleccionado
            archivo = fc.getSelectedFile();
            //Pongo en el label la informacion
            info.setText("Tamaño: "+archivo.length()+" bytes Ubicación: "+archivo.getPath());
            
            //Leemos el archivo y lo mostramos en pantalla
            try(BufferedReader br = new BufferedReader(new FileReader(archivo))) {
                
                //Usamos el iterador para recorrer cada linea
                Iterator<String> it = br.lines().iterator();
                while(it.hasNext()) {
                    //Creo un string para cada linea
                    String linea = it.next();
                    //Muestro en el text area cada linea
                    texto.append(linea + "\n");
                }

            } catch (FileNotFoundException ex) {
                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_abrirActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        
        //Creamos un file writer
        //Añadimos el parámetro false para que no añada nuevo texto, si no que
        //lo reemplace
        try(FileWriter fw = new FileWriter(archivo, false)) {
            
            //Sobreescribo el archivo
            fw.write(texto.getText());
            
        } catch (IOException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_guardarActionPerformed

    private void autorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorActionPerformed
        
        //He hecho que el JDialog salga con un tamaño adecuado
        hechoPor.setSize(400, 100);
        hechoPor.setVisible(true);
   
    }//GEN-LAST:event_autorActionPerformed

    private void guardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarComoActionPerformed

        //Ventana para seleccionar donde guardar
        int status = fc.showSaveDialog(null);

        //Al pulsar guardar el archivo pasa a ser el seleccionado
        if (status == JFileChooser.APPROVE_OPTION) {
            archivo = fc.getSelectedFile();
        }
        
        //Escribo en un archivo nuevo lo que quiera guardar
        try(FileWriter fw = new FileWriter(archivo, false)) {

            fw.write(texto.getText());
            
        } catch (IOException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_guardarComoActionPerformed

    private void colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorActionPerformed
        
        //Ajusto la ventana y la hago visible
        colorChooser.setSize(600, 300);
        colorChooser.setVisible(true);
        
    }//GEN-LAST:event_colorActionPerformed

    private void seleccionarColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarColorActionPerformed
        
        //Guardo el color de la fuente y se la pongo al texto
        colorFuente = colorSeleccionado.getColor();
        texto.setForeground(colorFuente);
        
    }//GEN-LAST:event_seleccionarColorActionPerformed

    private void fuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuenteActionPerformed
        
        //Ajusto la ventana y la hago visible
        fontChooser.setSize(100, 100);
        fontChooser.setVisible(true);
        
        //Pongo en el texto el tamaño actual de la fuente
        tamanhoFuente = ""+texto.getFont().getSize();
        fontSize.setText(tamanhoFuente);
        
    }//GEN-LAST:event_fuenteActionPerformed

    private void seleccionarTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarTamanhoActionPerformed
        
        //Convierto lo que haya escrito en el text field a entero
        //y se lo paso a una nueva fuente
        int t = parseInt(fontSize.getText());
        Font f = new Font(texto.getFont().getName(), texto.getFont().getStyle(), t);
        //Le pongo la nueva fuente al texto
        texto.setFont(f);
        
    }//GEN-LAST:event_seleccionarTamanhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //Aqui he hecho un par de cambios para que la ventana
                //salga con un tamaño mas adecuado
                Ventana Ventana = new Ventana();
                Ventana.setSize(600, 300);
                Ventana.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrir;
    private javax.swing.JMenuItem autor;
    private javax.swing.JMenuItem color;
    private javax.swing.JDialog colorChooser;
    private javax.swing.JColorChooser colorSeleccionado;
    private javax.swing.JDialog fontChooser;
    private javax.swing.JTextField fontSize;
    private javax.swing.JMenuItem fuente;
    private javax.swing.JMenuItem guardar;
    private javax.swing.JMenuItem guardarComo;
    private javax.swing.JDialog hechoPor;
    private javax.swing.JLabel info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JMenuItem salir;
    private javax.swing.JButton seleccionarColor;
    private javax.swing.JToggleButton seleccionarTamanho;
    private javax.swing.JTextArea texto;
    // End of variables declaration//GEN-END:variables
}
